### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by gtnarg** [jdereg/n-cube-editor#285]
Is there any "getting started" guide or information for setting up n-cube?

Tried building and deploying the war.  It appears to be expecting an Oracle database connection.

Regards,
Grant

```
SEVERE: Unable to create initial connections of pool.
java.sql.SQLException: Unable to load class: oracle.jdbc.driver.OracleDriver from ClassLoader:WebappClassLoader
  context: /n-cube-editor
  delegate: false
  repositories:
    /WEB-INF/classes/
----------> Parent Classloader:
org.apache.catalina.loader.StandardClassLoader@67fc85d
;ClassLoader:WebappClassLoader
  context: /n-cube-editor
  delegate: false
  repositories:
    /WEB-INF/classes/
----------> Parent Classloader:
org.apache.catalina.loader.StandardClassLoader@67fc85d

	at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:280)
	at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:200)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:708)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:642)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:464)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:141)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:115)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:102)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:126)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:77)
	at com.cedarsoftware.util.SpringConnectionProvider.getConnection(SpringConnectionProvider.groovy:41)
	at com.cedarsoftware.ncube.NCubeJdbcPersisterAdapter.jdbcOperation(NCubeJdbcPersisterAdapter.groovy:42)
	at com.cedarsoftware.ncube.NCubeJdbcPersisterAdapter.loadCube(NCubeJdbcPersisterAdapter.groovy:85)
	at com.cedarsoftware.ncube.NCubeManager.getCubeInternal(NCubeManager.groovy:265)
	at com.cedarsoftware.ncube.NCubeManager.checkPermissions(NCubeManager.groovy:2305)
	at com.cedarsoftware.ncube.NCubeManager.assertPermissions(NCubeManager.groovy:2246)
	at com.cedarsoftware.ncube.NCubeManager.assertPermissions(NCubeManager.groovy)
	at com.cedarsoftware.ncube.NCubeManager.getCube(NCubeManager.groovy:245)
	at com.cedarsoftware.ncube.NCubeManager.getApplicationID(NCubeManager.groovy:1865)
	at com.cedarsoftware.servlet.NCubeConfigurationProvider.<init>(NCubeConfigurationProvider.groovy:72)
	at com.cedarsoftware.servlet.JsonCommandServlet.init(JsonCommandServlet.groovy:79)
	at javax.servlet.GenericServlet.init(GenericServlet.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.tuckey.web.filters.urlrewrite.Run.fetchNewInstance(Run.java:582)
	at org.tuckey.web.filters.urlrewrite.Run.prepareRunObject(Run.java:338)
	at org.tuckey.web.filters.urlrewrite.Run.initialise(Run.java:188)
	at org.tuckey.web.filters.urlrewrite.Run.initialise(Run.java:133)
	at org.tuckey.web.filters.urlrewrite.RuleBase.initialise(RuleBase.java:284)
	at org.tuckey.web.filters.urlrewrite.NormalRule.initialise(NormalRule.java:118)
	at org.tuckey.web.filters.urlrewrite.Conf.initialise(Conf.java:440)
	at org.tuckey.web.filters.urlrewrite.Conf.<init>(Conf.java:132)
	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.loadUrlRewriterLocal(UrlRewriteFilter.java:289)
	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.loadUrlRewriter(UrlRewriteFilter.java:257)
	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.init(UrlRewriteFilter.java:248)
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:281)
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:262)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:107)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4775)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5452)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:633)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:976)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1653)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: Unable to load class: oracle.jdbc.driver.OracleDriver from ClassLoader:WebappClassLoader
  context: /n-cube-editor
  delegate: false
  repositories:
    /WEB-INF/classes/
```

**Comment by jdereg** [comment]
For starters, to see it running in action, visit http://ncube.io

Feel free to play around with that site.  I plan to eventually put up a
nice-looking main website, with a sign in page, and then a button to take
you to the actual N-Cube Editor.

This project is under very active development.  It is being used as a
Product Configurator for insurance products as well as general application
configuration support (complex configurations that are way beyond what a
properties file can describe).

On to your question...

In the beans.xml file you will see this section:

<bean id="ncubeDataSource" destroy-method="close"
class="org.apache.tomcat.jdbc.pool.DataSource"
      p:driverClassName="#{systemEnvironment['NCE_JDBC_DRIVER'] ?:
systemProperties['NCE_JDBC_DRIVER'] ?:
'oracle.jdbc.driver.OracleDriver'}"
      p:url="#{systemEnvironment['NCE_JDBC_URL'] ?:
systemProperties['NCE_JDBC_URL'] ?:
'jdbc:oracle:thin:@dm01np-scan.td.afg:1521/app_ncubed.dev.gai.com'}"
      p:username="#{systemEnvironment['NCE_JDBC_USER'] ?:
systemProperties['NCE_JDBC_USER'] ?: 'nce'}"
      p:password="#{systemEnvironment['NCE_JDBC_PWD'] ?:
systemProperties['NCE_JDBC_PWD'] ?: 'quality'}"
      p:jdbcInterceptors="com.cedarsoftware.util.PoolInterceptor"
      p:initialSize="5"
      p:minIdle="5"
      p:maxIdle="10"
      p:maxActive="100"
      p:maxWait="120000"
      p:jmxEnabled="true"
      p:removeAbandoned="true"
      p:removeAbandonedTimeout="180"
      p:testOnBorrow="true"
      p:testOnReturn="false"
      p:testWhileIdle="false"
      p:timeBetweenEvictionRunsMillis="30000"
      p:minEvictableIdleTimeMillis="30000"
      p:validationInterval="60000"
      p:validationQuery="#{systemEnvironment['NCE_POOL_QUERY'] ?:
systemProperties['NCE_POOL_QUERY'] ?: 'select 1 from dual'}">
</bean>

Either change the default Oracle settings, or set the appropriate
environment variables (or use -D system properties) for :

NCE_JDBC_DRIVER=mysql.blah

NCE_JDBC_URL=mysql:blah

NCE_JDBC_USER=bar

NCE_JDBC_PWD=foo

NCE_JDBC_POOL_QUERY=/* ping */   // for MySQL

**Comment by jdereg** [comment]
I've updated the readme.md file and added a Getting Started section.  Let me know if you have any further issues getting NCE up and running.
